### ISSUE TITLE
st-flash: incorrect file name handling

### ISSUE THREAD

**Issue by tdjastrzebski** [stlink-org/stlink#879] opened 2020-03-16 19:21 UTC
In case of incorrect bin file name **st-flash** fails with error:
`ERROR common.c: map_file() == -1`
I suggest more descriptive message.

**Comment by Nightwalker-87** [comment] 2020-03-17 21:43
So what would you suggest instead?

**Comment by tdjastrzebski** [comment] 2020-03-18 10:27
I suggest message:
`Unable to open [file-name] file.`

**Comment by Nightwalker-87** [comment] 2020-03-18 10:49
Ok, are you with Release v1.6.0 ?

**Comment by tdjastrzebski** [comment] 2020-03-18 13:05
So far so good :)
It seems to work better than 1.5.1 although I have not tested it extensively yet.

**Comment by Nightwalker-87** [comment] 2020-03-20 15:16
@tdjastrzebski: Can you submit a PR?

**Comment by Nightwalker-87** [comment] 2020-03-30 19:35
Duplicate of #650.

**Closed** 2020-04-12 13:24 UTC
Labels: code/feedback, component/st-flash, status/duplicate, status/no-bug, status/resolved
