### ISSUE TITLE
[reset] STM32F030: --reset option is not working

### ISSUE THREAD

**Issue by MrSpock** [stlink-org/stlink#261] opened 2014-09-01 17:58 UTC
How --reset switch is expected to work ?
Enable --reset doesn't have any impact on board.
On oscilloscope there is no pull-down for RESET line.
$ st-flash --reset write stm32f030_lab.bin 0x8000000
2014-09-01T19:56:13 INFO src/stlink-common.c: Loading device parameters....
2014-09-01T19:56:13 INFO src/stlink-common.c: Device connected is: F0 small device, id 0x10006444
2014-09-01T19:56:13 INFO src/stlink-common.c: SRAM size: 0x1000 bytes (4 KiB), Flash: 0x4000 bytes (16 KiB) in pages of 1024 bytes
2014-09-01T19:56:13 INFO src/stlink-common.c: Attempting to write 3008 (0xbc0) bytes to stm32 address: 134217728 (0x8000000)
Flash page at addr: 0x08000800 erased
2014-09-01T19:56:13 INFO src/stlink-common.c: Finished erasing 3 pages of 1024 (0x400) bytes
2014-09-01T19:56:13 INFO src/stlink-common.c: Starting Flash write for VL/F0 core id
2014-09-01T19:56:13 INFO src/stlink-common.c: Successfully loaded flash loader in sram
  2/2 pages written
2014-09-01T19:56:13 INFO src/stlink-common.c: Starting verification of write complete
2014-09-01T19:56:13 INFO src/stlink-common.c: Flash written and verified! jolly good!

**Comment by xor-gate** [comment] 2016-05-05 09:29
Your issue description is not very clear about programmer used, how it is connected. Please test with latest tools in master and newest stlink firmware.

**Comment by Nightwalker-87** [comment] 2020-03-19 13:37
@MrSpock: I am currently reviewing old leftovers.
Is this resolved with Release v1.2.0? Please verify.

**Comment by Nightwalker-87** [comment] 2020-06-17 13:41
I can reproduce this with a STM32F103C8T6 connected to a STLINK-v2/clone via 4-pin SWD.

**Comment by Ant-ON** [comment] 2021-03-20 18:53
@Nightwalker-87 Now it is difficult to say the reasons for this behavior. Perhaps the reset output of the programmer was not connected to the board. We saw oscillograms in the #220 that the reset works. I think we can close the problem as solved by  #1107.

**Closed** 2021-03-20 21:07 UTC
Labels: component/st-flash, error/reset, general/documentation, programmer/stlinkv2-clone, question, status/resolved, target/cks32f1, target/stm32f0
