### ISSUE TITLE
[reset] st-flash corrupts reset vector and following word

### ISSUE THREAD

**Issue by AJGBoomer** [stlink-org/stlink#264] opened 2014-09-17 19:25 UTC
A hexdump of the .bin file shows:
00000000  00 04 00 20 81 8a 00 08  c1 f6 00 08 d1 f6 00 08 : The reset vector is 0x08008a81
The file is flashed with st-flash starting at 0x8000000 as usual. This has worked in other projects.
The flash is dumped by st-flash read option and shows:
00000000  00 04 00 20 00 00 00 00  80 e2 00 00 d1 f6 00 08 : Reset vector is now 0 and following word is corrupted.And it really is. The processor takes an immediate hike to zero in gdb.
I am running Fedora release 20 on an I7 computer.
In Win7, I ran the ST-link tool on the same computer and successfully flashed the binary file.
St-Util -V99 info:
2014-09-17T15:16:39 DEBUG src/stlink-common.c: **\* stlink_core_id ***
2014-09-17T15:16:39 DEBUG src/stlink-common.c: core_id = 0x2ba01477
2014-09-17T15:16:39 DEBUG src/stlink-common.c: **\* stlink_read_debug32 10016413 is 0xe0042000
2014-09-17T15:16:39 DEBUG src/stlink-common.c: **\* stlink_read_debug32 400c000 is 0x1fff7a20
2014-09-17T15:16:39 INFO src/stlink-common.c: Device connected is: F4 device, id 0x10016413
2014-09-17T15:16:39 INFO src/stlink-common.c: SRAM size: 0x30000 bytes (192 KiB), Flash: 0x100000 bytes (1024 KiB) in pages of 16384 bytes
2014-09-17T15:16:39 DEBUG src/stlink-common.c: **\* looking up stlink version
2014-09-17T15:16:39 DEBUG src/stlink-common.c: st vid         = 0x0483 (expect 0x0483)
2014-09-17T15:16:39 DEBUG src/stlink-common.c: stlink pid     = 0x3748
2014-09-17T15:16:39 DEBUG src/stlink-common.c: stlink version = 0x2
2014-09-17T15:16:39 DEBUG src/stlink-common.c: jtag version   = 0x13
2014-09-17T15:16:39 DEBUG src/stlink-common.c: swim version   = 0x4
2014-09-17T15:16:39 DEBUG src/stlink-common.c: **\* stlink_reset ***
2014-09-17T15:16:39 INFO gdbserver/gdb-server.c: Chip ID is 00000413, Core ID is  2ba01477.
2014-09-17T15:16:39 DEBUG src/stlink-common.c: **\* reading target voltage
2014-09-17T15:16:39 DEBUG src/stlink-common.c: target voltage = 3227mV
2014-09-17T15:16:39 INFO gdbserver/gdb-server.c: Target voltage is 3227 mV.

Thanks for your help,

AJG

**Comment by Nightwalker-87** [comment] 2020-02-26 21:33
Unverified.

**Comment by Nightwalker-87** [comment] 2020-03-19 13:29
@AJGBoomer : I am currently reviewing old leftovers.
Is this resolved with Release v1.2.0? Please verify.

**Comment by Nightwalker-87** [comment] 2020-06-28 23:11
Can somebody with a STM32F4 try to reproduce this with our` v1.3.0-patch` branch?

**Comment by Nightwalker-87** [comment] 2021-04-11 20:51
@Ant-ON Do #277, #281 and/or #295 have any influence on this?

**Comment by Ant-ON** [comment] 2021-04-12 05:19
@Nightwalker-87 There is very little information here. It is only clear that the flash loader does not flash some of the data. With #295 is not related exactly.

**Comment by Nightwalker-87** [comment] 2021-05-02 19:20
Can someone try to reproduce this on a more recent version of Fedora (under most comparable circumstances) and give an assessment? @Vascom maybe?

**Comment by Nightwalker-87** [comment] 2021-05-16 23:43
Ping @vascom

**Comment by Vascom** [comment] 2021-05-17 05:40
> Ping @Vascom

I have no hardware to test stlink.

**Comment by Nightwalker-87** [comment] 2021-05-17 20:02
We can not assess this issue precisely, as there is too little information provided.
A review of issues from around the time this ticket was opened revealed that there was no general problem related to the observed behaviour. Thus we may assume the issue is not related to a malfunction in the toolset.

However we can give the general advice to refer to the [ST Microelectronics Programming manual (PM0214)](https://www.st.com/resource/en/programming_manual/dm00046982-stm32-cortex-m4-mcus-and-mpus-programming-manual-stmicroelectronics.pdf),
which provides detailed information on the exception model and appropriate fault handling.

**Closed by Nightwalker-87** 2021-05-17 20:02 UTC
Labels: component/st-flash, component/st-util, error/reset, os/linux, status/no-bug, status/resolved, target/stm32f4
