### ISSUE TITLE
Incorrect SN on Nucleo board

### ISSUE THREAD

**Issue by luckyluke72** [stlink-org/stlink#494] opened 2016-10-04 12:52 UTC
Programmer/board type: Stlink/v2-1 on NUCLEO board
Programmer firmware version: N/A
Operating system: Linux
Stlink tools version and/or git commit hash: v1.2.0-129-gee3f7a1
Stlink commandline tool name: st-info --serial
Target chip (and optional board): ANY

IMHO, there is an error in stlink_print_serial(stlink_t *sl, bool openocd), file src/tools/info.c:22

`line 30: fmt = "%02x";
`
should be replaced with 

`fmt="%c";
`
then  I noticed the SN is truncated, as the ST SN is 24 chars long. You have to extend the serial number array from 12 to 24 chars in some places in your code. In fact the real SN of the board should have been

0667 FF53 5651 7270 6761 3012
1. See for usb.c:912 stlink_probe_usb_devs(libusb_device *devs, stlink_t *sldevs[]) and following lines. In line 967 there is the call involved in SN, but you have to change

`usb.c:958 char serial[13]; 
`
array should be 25.
1. In  include/st-link.h:135 please change to the following
   
   `char serial[25];
   ` 
   Then it works

[ mar ott 04  14:45:03 ] celettol@celettol-HP-Compaq-Elite-8300-USDT:~/software/stlink/build$ ./st-info --serial
0667FF535651727067173012

I can send you the code if you like (or do a pull req.)

**Comment by xor-gate** [comment] 2016-10-09 19:37
The nucleo board programmer (stlinkv2-1) formats the serial in a hex-encoded string format (usb pid 0x374b). While stlink v1 and v2  format it is binary. It is already known this is incompatible, it needs more work than just changing the array to 25 elements. 

Thank you for your contribution, as this is a duplicate of #417 I will close this. Feel free to discus further in the other issue. Thanks!

**Comment by tarek-bochkati** [comment] 2021-03-16 23:02
#1106

**Closed** 2021-03-20 11:30 UTC
Labels: bug/fixed, code/refactoring, component/st-info, os/linux, programmer/stlinkv2, programmer/stlinkv2-1, status/duplicate, status/resolved
