### ISSUE TITLE
Nucleo-F401RE: Communication hangs after a while

### ISSUE THREAD

**Issue by fhars** [stlink-org/stlink#225] opened 2014-04-21 18:24 UTC
After a while, communication between st-util and my nucleo board fails.

It starts just fine, I can load a program and run it and use gdb on it as expected. Verbose output during this phase looks like:

```
2014-04-21T19:45:04 DEBUG src/stlink-common.c: stlink current mode: mass
2014-04-21T19:45:04 DEBUG src/stlink-common.c: stlink current mode: mass
2014-04-21T19:45:04 DEBUG src/stlink-common.c: *** stlink_enter_swd_mode ***
2014-04-21T19:45:04 INFO src/stlink-common.c: Loading device parameters....
2014-04-21T19:45:04 DEBUG src/stlink-common.c: *** stlink_core_id ***
2014-04-21T19:45:04 DEBUG src/stlink-common.c: core_id = 0x2ba01477
2014-04-21T19:45:04 DEBUG src/stlink-common.c: *** stlink_read_debug32 10006433 is 0xe0042000
2014-04-21T19:45:04 DEBUG src/stlink-common.c: *** stlink_read_debug32 200c000 is 0x1fff7a20
2014-04-21T19:45:04 INFO src/stlink-common.c: Device connected is: F4 device (Dynamic Efficency), id 0x10006433
2014-04-21T19:45:04 INFO src/stlink-common.c: SRAM size: 0x18000 bytes (96 KiB), Flash: 0x80000 bytes (512 KiB) in pages of 16384 bytes
2014-04-21T19:45:04 DEBUG src/stlink-common.c: *** looking up stlink version
2014-04-21T19:45:04 DEBUG src/stlink-common.c: st vid         = 0x0483 (expect 0x0483)
2014-04-21T19:45:04 DEBUG src/stlink-common.c: stlink pid     = 0x374b
2014-04-21T19:45:04 DEBUG src/stlink-common.c: stlink version = 0x2
2014-04-21T19:45:04 DEBUG src/stlink-common.c: jtag version   = 0x13
2014-04-21T19:45:04 DEBUG src/stlink-common.c: swim version   = 0x2
2014-04-21T19:45:04 DEBUG src/stlink-common.c: *** stlink_reset ***
2014-04-21T19:45:04 DEBUG src/stlink-common.c: *** reading target voltage
2014-04-21T19:45:04 DEBUG src/stlink-common.c: target voltage = 3246mV
2014-04-21T19:45:21 DEBUG src/stlink-common.c: *** stlink_force_debug_mode ***
2014-04-21T19:45:21 DEBUG src/stlink-common.c: *** stlink_reset ***
2014-04-21T19:45:21 DEBUG src/stlink-common.c: *** stlink_write_debug32 3 to 0xe0002000
2014-04-21T19:45:21 DEBUG src/stlink-common.c: *** stlink_read_debug32 261 is 0xe0002000
2014-04-21T19:45:21 DEBUG src/stlink-common.c: *** stlink_write_debug32 0 to 0xe0002008
2014-04-21T19:45:21 DEBUG src/stlink-common.c: *** stlink_write_debug32 0 to 0xe000200c
2014-04-21T19:45:21 DEBUG src/stlink-common.c: *** stlink_write_debug32 0 to 0xe0002010
2014-04-21T19:45:21 DEBUG src/stlink-common.c: *** stlink_write_debug32 0 to 0xe0002014
2014-04-21T19:45:21 DEBUG src/stlink-common.c: *** stlink_write_debug32 0 to 0xe0002018
2014-04-21T19:45:21 DEBUG src/stlink-common.c: *** stlink_write_debug32 0 to 0xe000201c
2014-04-21T19:45:21 DEBUG src/stlink-common.c: *** stlink_read_debug32 1 is 0xe000edfc
2014-04-21T19:45:21 DEBUG src/stlink-common.c: *** stlink_write_debug32 1000001 to 0xe000edfc
2014-04-21T19:45:21 DEBUG src/stlink-common.c: *** stlink_write_debug32 0 to 0xe0001028
2014-04-21T19:45:21 DEBUG src/stlink-common.c: *** stlink_write_debug32 0 to 0xe0001038
2014-04-21T19:45:21 DEBUG src/stlink-common.c: *** stlink_write_debug32 0 to 0xe0001048
2014-04-21T19:45:21 DEBUG src/stlink-common.c: *** stlink_write_debug32 0 to 0xe0001058
2014-04-21T19:45:22 DEBUG src/stlink-common.c: *** stlink_read_all_regs ***
2014-04-21T19:45:22 DEBUG src/stlink-common.c: *** stlink_read_all_regs ***
2014-04-21T19:45:22 DEBUG src/stlink-common.c: *** stlink_read_mem32 ***
2014-04-21T19:45:22 DEBUG src/stlink-common.c: *** stlink_read_reg
2014-04-21T19:45:22 DEBUG src/stlink-common.c:  (16) ***
2014-04-21T19:45:22 DEBUG src/stlink-usb.c: r_idx (16) = 0x01000000
2014-04-21T19:45:28 DEBUG src/stlink-common.c: *** stlink_run ***
2014-04-21T19:45:28 DEBUG src/stlink-common.c: *** stlink_status ***
2014-04-21T19:45:28 DEBUG src/stlink-common.c:   core status: running
2014-04-21T19:45:28 DEBUG src/stlink-common.c: *** stlink_status ***
2014-04-21T19:45:28 DEBUG src/stlink-common.c:   core status: running
2014-04-21T19:45:28 DEBUG src/stlink-common.c: *** stlink_status ***
2014-04-21T19:45:28 DEBUG src/stlink-common.c:   core status: running
2014-04-21T19:45:28 DEBUG src/stlink-common.c: *** stlink_status ***
2014-04-21T19:45:28 DEBUG src/stlink-common.c:   core status: running
2014-04-21T19:45:29 DEBUG src/stlink-common.c: *** stlink_status ***
2014-04-21T19:45:29 DEBUG src/stlink-common.c:   core status: running
2014-04-21T19:45:29 DEBUG src/stlink-common.c: *** stlink_status ***

```

The ST-LINK LED blinks red/green to signal ongoing communication.

But then after a while I get:

```
2014-04-21T19:58:31 DEBUG src/stlink-common.c: *** stlink_status ***
2014-04-21T19:58:31 DEBUG src/stlink-common.c:   core status: running
2014-04-21T19:58:31 DEBUG src/stlink-common.c: *** stlink_status ***
2014-04-21T19:58:31 DEBUG src/stlink-common.c:   core status: running
2014-04-21T19:58:31 DEBUG src/stlink-common.c: *** stlink_status ***
2014-04-21T19:58:31 DEBUG src/stlink-common.c:   core status: running
2014-04-21T19:58:31 DEBUG src/stlink-common.c: *** stlink_status ***
2014-04-21T19:58:31 DEBUG src/stlink-common.c:   core status: running
2014-04-21T19:58:32 DEBUG src/stlink-common.c: *** stlink_status ***
Chip ID is 00000433, Core ID is  2ba01477.
Target voltage is 3246 mV.
Listening at *:4242...
GDB connected.
libusb_handle_events() timeout
[!] send_recv
libusb_handle_events() timeout
[!] send_recv
libusb_submit_transfer(-6)
[!] send_recv
libusb_submit_transfer(-6)
[!] send_recv
libusb_submit_transfer(-6)
[!] send_recv
libusb_submit_transfer(-6)
[!] send_recv
libusb_submit_transfer(-6)
```

The program on the board continues running, and gdb still thinks it can talk to the server, but it can no longer actually affect the board, the ST-LINK LED swiches to green ("communication finished and successful"). st-util still continues to print the "core status: running" messages.

If I then quit st-util with Ctrl-C and restart it, I get:

```
2014-04-21T20:20:48 DEBUG src/stlink-common.c: stlink mode: unknown!
2014-04-21T20:20:48 DEBUG src/stlink-common.c: stlink mode: unknown!
2014-04-21T20:20:48 DEBUG src/stlink-common.c: *** stlink_enter_swd_mode ***
2014-04-21T20:20:48 INFO src/stlink-common.c: Loading device parameters....
2014-04-21T20:20:48 DEBUG src/stlink-common.c: *** stlink_core_id ***
2014-04-21T20:20:48 DEBUG src/stlink-common.c: core_id = 0x00000000
2014-04-21T20:20:48 DEBUG src/stlink-common.c: *** stlink_read_debug32 0 is 0xe0042000
2014-04-21T20:20:48 DEBUG src/stlink-common.c: *** stlink_read_debug32 0 is 0x40015800
2014-04-21T20:20:48 WARN src/stlink-common.c: unknown chip id! 0
2014-04-21T20:20:48 DEBUG src/stlink-common.c: *** looking up stlink version
2014-04-21T20:20:48 DEBUG src/stlink-common.c: st vid         = 0x0000 (expect 0x0483)
2014-04-21T20:20:48 DEBUG src/stlink-common.c: stlink pid     = 0x0000
2014-04-21T20:20:48 DEBUG src/stlink-common.c: stlink version = 0x0
2014-04-21T20:20:48 DEBUG src/stlink-common.c: jtag version   = 0x0
2014-04-21T20:20:48 DEBUG src/stlink-common.c: swim version   = 0x0
2014-04-21T20:20:48 DEBUG src/stlink-common.c:     notice: the firmware doesn't support a jtag/swd interface
2014-04-21T20:20:48 DEBUG src/stlink-common.c:     notice: the firmware doesn't support a swim interface
2014-04-21T20:20:48 DEBUG src/stlink-common.c: *** stlink_reset ***
2014-04-21T20:20:48 DEBUG src/stlink-common.c: *** reading target voltage
2014-04-21T20:20:48 DEBUG src/stlink-common.c: error reading target voltage
```

Powercycling the Nucleo board puts it in a usable state again.

**Comment by xor-gate** [comment] 2016-05-04 17:54
Please test against latest stlink master tools, and latest ST programmer firmware. Reopen a new issue when the problem still remains.

**Comment by Nightwalker-87** [comment] 2020-02-26 14:49
Is this reproducible with Release v1.2.0 or any later release? Seems to have gone down the sink... :-/

**Comment by Nightwalker-87** [comment] 2020-03-19 11:06
@fhars: I am currently reviewing old leftovers.
Is this resolved with Release v1.2.0? Please verify.

**Comment by Nightwalker-87** [comment] 2020-06-21 18:19
@chenguokai: I think this is a duplicate of issue 31. Am I right here?

**Comment by chenguokai** [comment] 2020-06-22 01:06
>  I think this is a duplicate of issue 31. Am I right here?

Not quite sure actually. Could be related but not sure that they are duplicates.

**Comment by Nightwalker-87** [comment] 2020-06-24 22:58
I think you are right on that. Nevertheless we need some verification here (preferably with `v1.3.0-patch`).

**Comment by Nightwalker-87** [comment] 2021-03-21 18:01
This problem is similar to a previously observed issue in #194. 
The observed behaviour could have resulted from a faulty `libusb` implementation (what is the primary expectation).
Nevertheless a firmware issue in the programmer may have also resulted in the corrupted USB connection.
`gdb` should indeed be able to detect a connection loss to the server.
However, as it is a stand-alone tool, this partial aspect is not related to the `stlink` toolset.

As the toolset-related issue has been addressed and one can safely assume that this is also the case for the aspects that derive from external tools, I am finally closing this issue now as resolved.

**Closed by Nightwalker-87** 2021-03-21 18:01 UTC
Labels: component/st-util, dependency/libusb, os/linux, status/resolved, target/stm32f4
