### ISSUE TITLE
Connection to USB Freezing

### ISSUE THREAD

**Issue by vaibhav-kapoor** [stlink-org/stlink#30] opened 2011-11-16 09:47 UTC
Hi, just wanted to mention really appreciate all the work you guys are doing.

I am running Fedora 16, and having incredible issues getting stm32f4discovery board working consistently.
I was able to get `./st-util` working and was able to load the code, but very quickly the microcontroller stops responding. This is the output on the `st-util`:

```
[!] send_recv
libusb_submit_transfer(-6)
[!] send_recv
libusb_submit_transfer(-6)
[!] send_recv
libusb_submit_transfer(-6)
[!] send_recv
libusb_submit_transfer(-6)
```

This occurs continuously, I can't stop the st-util process at all, no matter what I do. The continue command in gdb always hangs the st-util. It is an uninterruptable process. And the only way to fix it is to restart the computer. I couldn't find any way to the get it working without restarting the entire computer. GDB consistently hangs. I seem to get flash working relatively well, it doesn't hang to to much, but it happens after a while. I am having a bit of a tough time figuring everything out, but this is making things far more difficult. 

If I disconnect the board and reconnect it the LED close to USB blinks RED. A lot of the issues I can't seem to find info on anywhere, it doesn't looks like its a typical problem. Any help is really appreciated.

Also I noticed the makefiles for all the libraries on the recent update. I really appreciate this as well, for the last couple days I was working on getting the makefiles for the libraries, I had just finished gotten it working, but I can just use yours now. 

Again thanks for the help.
TheLegace

**Comment by xor-gate** [comment] 2016-05-17 18:28
Please test against `v1.2.0` or `master`, because this issue references a very old version of the stlink tools. Feel free to open a new issue if the problem still remains.

**Comment by Nightwalker-87** [comment] 2020-06-14 15:42
I know this references a very old libusb-version. However we may give it another try with our `v1.3.0-patch`  branch (the oldest one with a working compilation) with some real hardware (any `0x2ba01477`). If this does not produce the described output, we would be able to close this with a solution and reference this ticket correctly . Can somebody help out?

**Comment by Nightwalker-87** [comment] 2020-06-19 22:41
@Vascom with your Fedora system maybe?

**Comment by Vascom** [comment] 2020-06-20 02:43
I think this issue should be closed :)

**Comment by Nightwalker-87** [comment] 2020-06-20 10:25
No, I don't simply close tickets just because they are old. There should be either a verification or another solved ticket that addresses the same issue. Here we have the chance to verify with Fedora (whatever version available) and `v1.3.0-patch` , so we should do it. This is also one reason why the `patch-branches` are still there.

**Comment by Nightwalker-87** [comment] 2020-06-20 23:01
@Vascom: Could you test anyway?

**Comment by Vascom** [comment] 2020-06-21 20:10
I can't test because I have not hardware for it. I am only maintain package.
Anyway old Fedora releases not suppurted and should not be used. All bugs on unsupported releases should be closed and user must try new release.

**Comment by Nightwalker-87** [comment] 2020-06-21 20:22
> I can't test because I have not hardware for it. I am only maintain package.

I understand, so we would need somebody else for this task.

> Anyway old Fedora releases not suppurted and should not be used. All bugs on unsupported releases should be closed and user must try new release.

I know, that's why I wrote "whatever version available" ...

**Comment by Nightwalker-87** [comment] 2020-06-26 00:00
Are there any other fedora users that can help to verify this with real hardware?

**Comment by Nightwalker-87** [comment] 2020-10-24 14:35
Are there any other fedora users that can help to verify this with real hardware?

**Comment by Nightwalker-87** [comment] 2020-12-14 00:36
Fedora 16 used libusb 1.0.9.

**Comment by Nightwalker-87** [comment] 2021-03-09 23:49
Conclusion: This issue was likely related to a kernel-bug and/or a bug in relation to the libusb library on Fedora 16.
As support for Fedora 16 has ended a long time ago and we already know from the original author that the observed behaviour did not occur on a obviously comparable Ubuntu system at that time, we can safely assume that this problem is no longer reproducible.

**Closed by Nightwalker-87** 2021-03-09 23:49 UTC
Labels: component/st-util, dependency/libusb, needs/investigation, needs/testing, os/linux, target/stm32f4
