### ISSUE TITLE
stm32f411re: Flash programming error 0x40

### ISSUE THREAD

**Issue by sparkdragon586** [stlink-org/stlink#1340] opened 2023-10-07 03:11 UTC
**Thank you for giving feedback to the stlink project.**

---

**NOTE: In order to offer sufficient and the best possible support, please read /CONTRIBUTING.md and follow the given instructions _before_ submitting a ticket.**

**Bug reports and/or feature requests will be deleted, if they violate our contribution guidelines and if no issue-template is used!** Thank you for your support.

---

- [x] I made serious effort to avoid creating duplicate or nearly similar issue

In order to allow developers to isolate and target your respective issue, please take some time to select the check boxes below and fill out each of the following items appropriate to your specific problem.

- [x] Programmer/board type: ST-link-V2 (e.g STLINK /V1, /V2, /V2-onboard, /V2-clone, /V3)
- [x] Operating system an version: [arch up to date] (e.g Linux, Windows)
- [x] **stlink tools version** and/or git commit hash: [V1.7] (e.g v1.6.1/git-d0416149)
- [x] stlink commandline tool name: [st-flash] (e.g `st-info`, `st-flash`, `st-trace`, `st-util`)
- [x] Target chip (and board, if applicable): [blackpill] (e.g STM32F103C8T6 (NUCLEO-F103RB))

Further we kindly ask you to describe the detected problem as detailed as possible and to add debug output if available, by using the following template:

Commandline output:

```
❯ st-flash --debug write tmp.bin 0x08000000
st-flash 1.7.0
2023-10-06T21:01:32 DEBUG common.c: *** looking up stlink version
2023-10-06T21:01:32 DEBUG common.c: st vid         = 0x0483 (expect 0x0483)
2023-10-06T21:01:32 DEBUG common.c: stlink pid     = 0x3748
2023-10-06T21:01:32 DEBUG common.c: stlink version = 0x2
2023-10-06T21:01:32 DEBUG common.c: jtag version   = 0x2b
2023-10-06T21:01:32 DEBUG common.c: swim version   = 0x7
2023-10-06T21:01:32 DEBUG common.c: stlink current mode: dfu
2023-10-06T21:01:32 DEBUG usb.c: -- exit_dfu_mode
2023-10-06T21:01:32 DEBUG common.c: *** stlink_exit_dfu_mode ***
2023-10-06T21:01:32 DEBUG usb.c: JTAG/SWD freq set to 0
2023-10-06T21:01:32 DEBUG common.c: *** set_swdclk ***
2023-10-06T21:01:33 DEBUG common.c: stlink current mode: mass
2023-10-06T21:01:33 DEBUG common.c: *** stlink_enter_swd_mode ***
2023-10-06T21:01:33 DEBUG common.c: Loading device parameters....
2023-10-06T21:01:33 DEBUG common.c: *** stlink_core_id ***
2023-10-06T21:01:33 DEBUG common.c: core_id = 0x2ba01477
2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_debug32 0x410fc241 at 0xe000ed00
2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_debug32 0x10006431 at 0xe0042000
2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_debug32 0x0200c000 at 0x1fff7a20
2023-10-06T21:01:33 INFO common.c: stm32f411re: 128 KiB SRAM, 512 KiB flash in at least 16 KiB pages.
2023-10-06T21:01:33 DEBUG common.c: stlink current mode: debug (jtag or swd)
2023-10-06T21:01:33 DEBUG common.c: stlink current mode: debug (jtag or swd)
2023-10-06T21:01:33 DEBUG common.c: *** stlink_force_debug_mode ***
2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_debug32 0000000000 at 0xe0042008
2023-10-06T21:01:33 DEBUG common.c: *** stlink_write_debug32 0x00001800 to 0xe0042008
2023-10-06T21:01:33 DEBUG common.c: *** stlink_status ***
2023-10-06T21:01:33 DEBUG usb.c: core status: 03030003
2023-10-06T21:01:33 DEBUG common.c:   core status: halted
file tmp.bin md5 checksum: 6ae59e6485377ee5470c854761551ea, stlink checksum: 0x000ff000
2023-10-06T21:01:33 INFO common.c: Attempting to write 4096 (0x1000) bytes to stm32 address: 134217728 (0x8000000)
2023-10-06T21:01:33 DEBUG common.c: *** stlink_core_id ***
2023-10-06T21:01:33 DEBUG common.c: core_id = 0x2ba01477
2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_debug32 0000000000 at 0x40023c0c
2023-10-06T21:01:33 DEBUG common.c: *** stlink_write_debug32 0x000000f0 to 0x40023c0c
2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_debug32 0x80000000 at 0x40023c10
2023-10-06T21:01:33 DEBUG common.c: *** stlink_write_debug32 0x45670123 to 0x40023c04
2023-10-06T21:01:33 DEBUG common.c: *** stlink_write_debug32 0xcdef89ab to 0x40023c04
2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_debug32 0000000000 at 0x40023c10
2023-10-06T21:01:33 DEBUG common.c: Successfully unlocked flash
EraseFlash - Sector:0x0 Size:0x4000 2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_debug32 0000000000 at 0x40023c10
2023-10-06T21:01:33 DEBUG common.c: *** stlink_write_debug32 0x00000002 to 0x40023c10
2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_debug32 0x00000002 at 0x40023c10
2023-10-06T21:01:33 DEBUG common.c: *** stlink_write_debug32 0x00010002 to 0x40023c10
2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_debug32 0x00010000 at 0x40023c0c
2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_debug32 0x00010000 at 0x40023c0c
[Same for a while]
2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_debug32 0x00010000 at 0x40023c0c
2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_debug32 0000000000 at 0x40023c0c
2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_debug32 0x00000002 at 0x40023c10
2023-10-06T21:01:33 DEBUG common.c: *** stlink_write_debug32 0x80000002 to 0x40023c10
2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_debug32 0000000000 at 0x40023c0c
2023-10-06T21:01:33 INFO common.c: Flash page at addr: 0x08000000 erased
2023-10-06T21:01:33 INFO common.c: Finished erasing 1 pages of 16384 (0x4000) bytes
2023-10-06T21:01:33 DEBUG common.c: *** stlink_write_debug32 0xa05f0003 to 0xe000edf0
2023-10-06T21:01:33 DEBUG common.c: *** stlink_write_debug32 0xa05f000b to 0xe000edf0
2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_debug32 0000000000 at 0x40023830
2023-10-06T21:01:33 DEBUG common.c: *** stlink_write_debug32 0000000000 to 0x40023830
2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_debug32 0000000000 at 0x40023c0c
2023-10-06T21:01:33 DEBUG common.c: *** stlink_write_debug32 0x000000f0 to 0x40023c0c
2023-10-06T21:01:33 INFO common.c: Starting Flash write for F2/F4/F7/L4
2023-10-06T21:01:33 DEBUG common.c: *** reading target voltage
2023-10-06T21:01:33 DEBUG common.c: target voltage = 2420mV
2023-10-06T21:01:33 DEBUG common.c: *** stlink_write_mem32 48 bytes to 0x20000000
2023-10-06T21:01:33 INFO flash_loader.c: Successfully loaded flash loader in sram
2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_debug32 0x00000001 at 0xe000ed30
2023-10-06T21:01:33 INFO flash_loader.c: Clear DFSR
2023-10-06T21:01:33 DEBUG common.c: *** stlink_write_debug32 0x00000001 to 0xe000ed30
2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_debug32 0x00001001 at 0xe000ed28
2023-10-06T21:01:33 INFO flash_loader.c: Clear CFSR
2023-10-06T21:01:33 DEBUG common.c: *** stlink_write_debug32 0x00001001 to 0xe000ed28
2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_debug32 0x40000000 at 0xe000ed2c
2023-10-06T21:01:33 INFO flash_loader.c: Clear HFSR
2023-10-06T21:01:33 DEBUG common.c: *** stlink_write_debug32 0x40000000 to 0xe000ed2c
2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_debug32 0x80000002 at 0x40023c10
2023-10-06T21:01:33 DEBUG common.c: *** stlink_write_debug32 0x45670123 to 0x40023c04
2023-10-06T21:01:33 DEBUG common.c: *** stlink_write_debug32 0xcdef89ab to 0x40023c04
2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_debug32 0x00000002 at 0x40023c10
2023-10-06T21:01:33 DEBUG common.c: Successfully unlocked flash
2023-10-06T21:01:33 DEBUG common.c: *** reading target voltage
2023-10-06T21:01:33 DEBUG common.c: target voltage = 3021mV
2023-10-06T21:01:33 INFO common.c: enabling 32-bit flash writes
2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_debug32 0x00000002 at 0x40023c10
2023-10-06T21:01:33 DEBUG common.c: *** stlink_write_debug32 0x00000202 to 0x40023c10
2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_debug32 0x00000202 at 0x40023c10
2023-10-06T21:01:33 DEBUG common.c: *** stlink_write_debug32 0x00000203 to 0x40023c10
2023-10-06T21:01:33 DEBUG flash_loader.c: Running flash loader, write address:0x8000000, size: 4096
2023-10-06T21:01:33 DEBUG common.c: *** stlink_write_mem32 4096 bytes to 0x20000030
2023-10-06T21:01:33 DEBUG common.c: *** stlink_write_reg
2023-10-06T21:01:33 DEBUG common.c: data_len = 2 0x2
 80 00
2023-10-06T21:01:33 DEBUG common.c: *** stlink_write_reg
2023-10-06T21:01:33 DEBUG common.c: data_len = 2 0x2
 80 00
2023-10-06T21:01:33 DEBUG common.c: *** stlink_write_reg
2023-10-06T21:01:33 DEBUG common.c: data_len = 2 0x2
 80 00
2023-10-06T21:01:33 DEBUG common.c: *** stlink_write_reg
2023-10-06T21:01:33 DEBUG common.c: data_len = 2 0x2
 80 00
2023-10-06T21:01:33 DEBUG common.c: *** stlink_write_reg
2023-10-06T21:01:33 DEBUG common.c: data_len = 2 0x2
 80 00
2023-10-06T21:01:33 DEBUG common.c: *** stlink_write_debug32 0x0000aaaa to 0x40003000
2023-10-06T21:01:33 DEBUG common.c: *** stlink_run ***
2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_reg
2023-10-06T21:01:33 DEBUG common.c:  (16) ***
2023-10-06T21:01:33 DEBUG common.c: data_len = 8 0x8
 80 00 00 00 03 00 00 01
2023-10-06T21:01:33 DEBUG usb.c: r_idx (16) = 0x01000003
2023-10-06T21:01:33 DEBUG common.c: *** stlink_status ***
2023-10-06T21:01:33 DEBUG usb.c: core status: 0103000B
2023-10-06T21:01:33 DEBUG common.c:   core status: halted
2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_reg
2023-10-06T21:01:33 DEBUG common.c:  (2) ***
2023-10-06T21:01:33 DEBUG common.c: data_len = 8 0x8
 80 00 00 00 00 00 00 00
2023-10-06T21:01:33 DEBUG usb.c: r_idx ( 2) = 0x00000000
2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_debug32 0x00000040 at 0x40023c0c
2023-10-06T21:01:33 ERROR common.c: Flash programming error: 0x00000040
2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_debug32 0xffffffff at 0x08000000
2023-10-06T21:01:33 DEBUG common.c: *** stlink_write_reg
2023-10-06T21:01:33 DEBUG common.c: data_len = 2 0x2
 0d 00
2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_debug32 0xffffffff at 0x08000004
2023-10-06T21:01:33 DEBUG common.c: *** stlink_write_reg
2023-10-06T21:01:33 DEBUG common.c: data_len = 2 0x2
 80 00
2023-10-06T21:01:33 DEBUG common.c: *** stlink_run ***
2023-10-06T21:01:33 DEBUG common.c: *** stlink_read_reg
2023-10-06T21:01:33 DEBUG common.c:  (16) ***
2023-10-06T21:01:33 DEBUG common.c: data_len = 8 0x8
 80 00 00 00 03 00 00 61
2023-10-06T21:01:33 DEBUG usb.c: r_idx (16) = 0x61000003
stlink_fwrite_flash() == -1
2023-10-06T21:01:33 DEBUG common.c: *** stlink_exit_debug_mode ***
2023-10-06T21:01:33 DEBUG common.c: *** stlink_write_debug32 0xa05f0000 to 0xe000edf0
2023-10-06T21:01:33 DEBUG common.c: *** stlink_close ***


```

Expected/description:

st-flash and stlink-gui fail to write flash (they erase) no matter what I try. st-info shows valid info. Sorry if this is super simple or not enough info. feel free to ask for more info.

**Comment by Nightwalker-87** [comment] 2023-12-25 13:27
Can someone with a blackpill board (STM32F411RE) please try to reproduce this issue?

**Comment by darkmoon32** [comment] 2024-01-03 07:06
@Nightwalker-87 I do not have blackpill board but I have tested it with Nucleo-F411RE if that helps.  I was not able to reproduce the issue. Perhaps it is a HW issue because the boards' voltage is a little low.
[st-flash.txt](https://github.com/stlink-org/stlink/files/13816383/st-flash.txt)

**Comment by Nightwalker-87** [comment] 2024-01-04 12:24
@darkmoon32 Thank you very much for reporting back. :wink: 
The fact that the issue is not reproducible with the same chip is good news.
It indicates that there is no general issue with the toolset itself related to this reporting.
Thus we shall be fine to close this ticket as resolved and verified.
One may open a new issue anytime, if a hardware issue can be definitely ruled out.

**Closed by Nightwalker-87** 2024-01-04 12:24 UTC
Labels: os/linux, needs/investigation, target/stm32f4, component/st-flash, programmer/STLINK/V2, needs/testing
