### ISSUE TITLE
Windows st-util could not retrieve port number for device

### ISSUE THREAD

**Issue by xtrinch** [stlink-org/stlink#623] opened 2017-07-29 15:54 UTC
Trying to run st-util on windows 10 for connected board STM32F769I-DISCO:

```
C:\Users\trinch> st-info --probe
Found 1 stlink programmers
```

```
PS C:\Users\trinch> st-info --chipid
libusb: warning [windows_get_device_list] could not retrieve port number for device '\\.\USBESTUB#DEVICES#0004', skipping: [13] The data is invalid.
libusb: warning [windows_get_device_list] could not retrieve port number for device '\\.\USBESTUB#DEVICES#0000', skipping: [13] The data is invalid.
0x0451
```

```
PS C:\Users\trinch> st-info --descr
libusb: warning [windows_get_device_list] could not retrieve port number for device '\\.\USBESTUB#DEVICES#0004', skipping: [13] The data is invalid.
libusb: warning [windows_get_device_list] could not retrieve port number for device '\\.\USBESTUB#DEVICES#0000', skipping: [13] The data is invalid.
F76xxx device
```

```
C:\Users\trinch> st-util
STLINK GDB Server v0.5.6 (Mar 24 2013 10:29:19)
Many thanks to the STLINK development team.
(https://github.com/texane/stlink)

2017-07-29T17:48:37 WARN src/stlink-usb.c: Couldn't find any ST-Link/V2 devices
```

Though, I can program my device with ST-LINK_CLI.

```
PS C:\Users\trinch> st-link_cli -List
STM32 ST-LINK CLI v3.0.0.0
STM32 ST-LINK Command Line Interface

--- Available ST-LINK Probes List ---

ST-LINK Probe 0:
     SN: 0672FF524853837267132010
     FW: V2J27M15

----------------------------------
```

Help?

**Comment by Nightwalker-87** [comment] 2020-02-23 00:16
@xtrinch which libusb version is used? Please also test this with Release v1.4.0, v1.5.0, v1.5.1 and v.1.6.0, which have been released in the meanwhile, as this issue is already very old.

**Comment by Nightwalker-87** [comment] 2020-03-22 01:13
ping @xtrinch

**Comment by slyshykO** [comment] 2020-03-22 05:22
@Nightwalker-87, Think it is connected with #438 also.

**Comment by Nightwalker-87** [comment] 2020-03-23 14:43
> ```
> PS C:\Users\trinch> st-info --chipid
> libusb: warning [windows_get_device_list] could not retrieve port number for device '\\.\USBESTUB#DEVICES#0004', skipping: [13] The data is invalid.
> libusb: warning [windows_get_device_list] could not retrieve port number for device '\\.\USBESTUB#DEVICES#0000', skipping: [13] The data is invalid.
> 0x0451
> 
> PS C:\Users\trinch> st-info --descr
> libusb: warning [windows_get_device_list] could not retrieve port number for device '\\.\USBESTUB#DEVICES#0004', skipping: [13] The data is invalid.
> libusb: warning [windows_get_device_list] could not retrieve port number for device '\\.\USBESTUB#DEVICES#0000', skipping: [13] The data is invalid.
> F76xxx device
> ```

@slyshykO: Yes, this obviously is the same as in your MinGW test there.

Duplicate of #438.

**Comment by xtrinch** [comment] 2020-03-24 08:00
Can't offer feedback which version of libusb it was as I don't have the setup anymore

**Comment by Nightwalker-87** [comment] 2020-03-24 09:36
@xtrinch: That was expected due to the time passed. We're fine with this.
I think it will not affect us here as we also have #438.

**Closed** 2020-04-10 20:22 UTC
Labels: bug/needs-investigation, component/st-info, component/st-util, dependency/libusb, os/windows, target/stm32f7
