### ISSUE TITLE
[reset] Unable to reset board in gdb

### ISSUE THREAD

**Issue by dflogeras** [stlink-org/stlink#254] opened 2014-08-04 17:35 UTC
I am using ChibiOS-2.6.5 and attempting to integrate the CMSIS library for DSP functionality.

My board is a STM32F407-Discovery and my toolchain was generated using Gentoo's crossdev package, with the following:
gcc-4.7.3 (compiled arm-hardfloat-eabi)
binutils-2.23.2
newlib-2.0.0
gdb-7.6.2

So far, the process of compile, flash, debug, repeat has worked great on this, as well as another project using a STM32L151 chip.

After adding linking the CMSIS library into my project, I have found that I cannot debug reliably.  If I attach to the gdb server, it will often be in the ChibiOS unhandled_exception() handler, or maybe __gnu_unwind_execute(), I assume after hitting an exception condition.

Oddly though, I cannot reset the board in gdb with kill/run.  Doing so ends up right where it was before, even with a breakpoint in the ResetHandler() function.  Even pressing the reset button on the devkit doesn't reset it.  I have to use 'load' with gdb, sometimes pressing the reset button while loading the firmware before it works fully.

I am wondering if this is a known issue, and if there is anything I can do to debug or work around it?

**Comment by xor-gate** [comment] 2016-05-14 15:48
Please test against `v1.2.0` or `master` and report if the problem still exists.

**Comment by dflogeras** [comment] 2016-05-17 12:39
I can reliably debug with my current toolchain and stlink on a STM32F4 CMSIS project.  Unfortunately I cannot easily go back to the toolchain I had 2 years ago, but I doubt it has much value.

I did notice while testing that doing a kill/run in gdb would produce:

Starting program: /home/dave/ChibiOS_3.0.5/stm32f4_test/build/ch.elf 
inferior.c:361: internal-error: find_inferior_pid: Assertion `pid != 0' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Quit this debugging session? (y or n)

I found that I can:
a) Instead of kill/run, I can kill, then "target remote :4242" to re-attach and it is waiting for me in ResetHandler()
b) Upgrade gdb from 7.10.1 to 7.11 and the issue seems to  go away

Is this expected?

**Comment by xor-gate** [comment] 2016-05-17 17:19
Thank you for testing, that is a good answer. I have currently no clue what is expected (by others) and why it is solved by using gdb 7.11. I have seen similar problems when running under ChibiOS RTOS also under OpenOCD.

**Comment by rewolff** [comment] 2016-05-21 11:23
To me: "even pressing the reset button doesn't reset it" is a red flag. The hardware reset should always work. 

What possibly might not be working is that the debugger catches the processor as it comes out of reset. In that case Chibios will be crashed in "unhandled exception" before you get to move your finger from the reset button to your keyboard.

**Comment by xor-gate** [comment] 2016-05-21 11:27
You are right, I have no clue how OpenOCD handles this nicely. Again the gdb-stubs in stlink are in a very bad shape currently (as you know yourself).

**Comment by xor-gate** [comment] 2016-12-30 11:03
Closing this due to inactivity and oldness. Feel free to open a new issue when te problem remains. I have just merged a possible fix from PR #534.

**Comment by Nightwalker-87** [comment] 2020-03-20 13:14
@dflogeras  @rewolff: What is the current state here?

**Comment by rewolff** [comment] 2020-03-20 14:40
I don't know. 
It is not something I'm able to reproduce. I'd say with the "reset through SWD" improvements that I can test for in 1.6.0, this stands a chance of having been a manifestation of the same bug and therefore fixed by the same update. 
I suggest closing this unless someone shows up saying it can still be reproduced.

**Comment by dflogeras** [comment] 2020-03-20 15:42
I agree, this was so long ago I would be very difficult for me to reproduce.  Let's close it.

**Comment by Nightwalker-87** [comment] 2020-03-20 15:56
Thx for the feedback you two.
@rewolff: I'm just thinking about the correct issue number one should link this to when closing it. This is currently quite difficult and confusing, as there are so many cross-references between related issues. Can you make a useful proposal, as you seem to be in the topic quite well...

**Comment by rewolff** [comment] 2020-03-20 16:33
It seems that in the past lots of issues were closed after nobody had done anything for say more than 3 years. I think it is a good idea to go through the old issues to reopen them to see if it has been fixed. But it seems you are also trying to tag the precise fix that fixed this. 
I think that's a waste of effort. When an old issue "seems fixed" just close it with "was fixed with or before 1.6.0" and be done with it. 
So my suggestion is to just close it.

**Comment by Nightwalker-87** [comment] 2020-03-23 16:01
I'll leave this for now to focus on the other stuff needed for Release v1.6.1.
It will neither get "lost" nor "forgotten" for a second time as all issues with a unclear or open state now remain in a separate milestone and _every_ issue is tagged to a milestone.
Also all new releases will be maintained as projects.

**Comment by rewolff** [comment] 2020-03-23 16:10
What timeframe are we looking at for 1.6.1? I've found some problems that I seem to have caused, so I need to fix it....

**Comment by Nightwalker-87** [comment] 2020-03-23 16:14
This is displayed on the milestone for every upcoming release.
For v1.6.1 I considered June 2020 for now, which may be subject to change according to workload and contributions.

**Comment by rewolff** [comment] 2020-03-23 16:31
I aim to fix stuff I've seen this week. Bother me if you don't hear from me.

**Comment by Ant-ON** [comment] 2021-03-31 08:09
I think it can be closed by #1071
The problem is most likely due to the reset pin not being connected. In older versions of the `st-util`, the reset through the SWD was not implemented

**Comment by Nightwalker-87** [comment] 2021-04-04 00:17
The observed behaviour obviously derived from the following issues:
- Bug in the external debugging tool `gdb` 7.10.1 which appears to have been fixed in v7.11.
- Missing ability for a software reset via the SWD interface that was not present before #712.
- Further improvements for the software-based reset functionality have been added in #1071.

With this conclusion based on a final review of the related topic we can safely close this ticket as resolved.

**Closed by Nightwalker-87** 2021-04-04 00:17 UTC
Labels: error/gdb-server, error/reset, needs/investigation, os/linux, programmer/stlinkv2-1, target/stm32f4
