### ISSUE TITLE
[feature] Caching and diffing bin/hex

### ISSUE THREAD

**Issue by lefebvresam** [stlink-org/stlink#1366] opened 2024-02-05 10:42 UTC
In most of the cases when you are programming you only change small pieces of code. It means that the bin/hex is changed only  slightly based on the previous one. When you program the device, all blocks are programmed again. It means that even when you change a small string value, all 40 or 50 memory blocks are re-programmed again and you have to wait all the times for 40sec because the max programming speed is 4Mbps. Should it be possible to check which blocks have been changed based on the previous bin/hex and only program those which are different? It could speedup the development cycle a lot. It could be an option to provide --non-caching or something like that to reprogram the whole flash.

**Comment by Nightwalker-87** [comment] 2024-02-05 20:43
Likely a duplicate of #1238.

**Comment by Nightwalker-87** [comment] 2024-08-02 18:58
Addressed in #1397.

**Closed as completed by Nightwalker-87** 2024-08-02 18:58 UTC
Labels: code/feature-request, component/st-flash, component/stlink-lib, status/resolved, status/duplicate
