### ISSUE TITLE
Nucleo-F091RC: st-util can't flash firmware

### ISSUE THREAD

**Issue by master-q** [stlink-org/stlink#597] opened 2017-05-20 08:13 UTC
There is rare case that st-util can't flash firmware onto NUCLEO-F091RC.

- [X] Programmer/board type: Stlink/v2-1-onboard
- [X] Programmer firmware version: v1.3.1-19-g55c0572
- [X] Operating system: Debian GNU/Linux sid
- [X] Stlink tools version and/or git commit hash: 55c057296ad15fa6de9909206098bd4eed8f6311
- [X] Stlink commandline tool name: `st-util`
- [X] Target chip (and optional board): STM32F091RCT6 on NUCLEO-F091RC

`st-util` output:

```
$ sudo st-util
--snip--
2017-05-20T17:04:06 ERROR src/gdbserver/gdb-server.c: cannot recv: -2
2017-05-20T17:04:07 INFO src/gdbserver/gdb-server.c: Listening at *:4242...
2017-05-20T17:04:07 INFO src/gdbserver/gdb-server.c: Found 4 hw breakpoint registers
2017-05-20T17:04:07 INFO src/gdbserver/gdb-server.c: GDB connected.
2017-05-20T17:04:08 INFO src/gdbserver/gdb-server.c: Found 4 hw breakpoint registers
2017-05-20T17:04:09 INFO src/common.c: Attempting to write 2048 (0x800) bytes to stm32 address: 134217728 (0x8000000)
Flash page at addr: 0x08000000 erased
2017-05-20T17:04:09 INFO src/common.c: Finished erasing 1 pages of 2048 (0x800) bytes
2017-05-20T17:04:09 INFO src/common.c: Starting Flash write for VL/F0/F3/F1_XL core id
2017-05-20T17:04:09 INFO src/flash_loader.c: Successfully loaded flash loader in sram
2017-05-20T17:04:13 ERROR src/flash_loader.c: flash loader run error
2017-05-20T17:04:13 ERROR src/common.c: stlink_flash_loader_run(0x8000000) failed! == -1
```

`gdb` output:

```
$ cat ../gdbwrite.boot
tar ext localhost:4242
monitor reset halt
load
monitor reset halt
$ arm-none-eabi-gdb -x ../gdbwrite.boot build/ch.elf
GNU gdb (7.12-6+9+b2) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=x86_64-linux-gnu --target=arm-none-eabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from build/ch.elf...done.
_idle_thread.lto_priv.58 (p=0x0) at ../../../ChibiOS_16.1.6/os/rt/src/chsys.c:65
65      static void _idle_thread(void *p) {
Loading section startup, size 0xc0 lma 0x8000000
Loading section .text, size 0x62fc lma 0x80000c0
Loading section .data, size 0xb8 lma 0x80063c0
../gdbwrite.boot:3: Error in sourced command file:
Error finishing flash operation
```

Expected/description: I think gdb can do flash everytime.

**Comment by xor-gate** [comment] 2017-06-10 20:35
Could you try a little older commit from the master branch? Probably there is something wrong with the flash locking/unlocking.

**Comment by master-q** [comment] 2017-06-10 22:21
O.K. I'll try that. Please give me some times....

**Comment by Nightwalker-87** [comment] 2020-03-20 11:22
@master-q: Has there been any further progress on this (e.g. a test with Release v1.4.0) ?

**Comment by Nightwalker-87** [comment] 2020-07-05 14:23
This should be tested again with the `v1.5.0-patch` branch.

**Comment by rileylyman** [comment] 2020-08-20 18:18
I'm having the exact same issue on v1.6.1

**Comment by Nightwalker-87** [comment] 2021-03-24 18:13
@Ant-ON Can you check this one as well? I think though `st-util` was used, this may also be addressed by #1113.

**Comment by Ant-ON** [comment] 2021-03-25 03:00
@Nightwalker-87 Standard error descriptions are not informative. Most likely this issue is closed by #1113.

**Comment by Nightwalker-87** [comment] 2021-03-25 07:00
Yeah, true. However, as the error code
```
2017-05-20T17:04:13 ERROR src/flash_loader.c: flash loader run error
2017-05-20T17:04:13 ERROR src/common.c: stlink_flash_loader_run(0x8000000) failed! == -1
```
is identical to what we've seen before one should be safe to assume the issue is fixed by now.

**Comment by Ant-ON** [comment] 2021-03-25 07:47
@Nightwalker-87 Yes, otherwise someone with the error can open a new issue with a new log

**Closed** 2021-03-25 14:21 UTC
Labels: bug/fixed, bug/regression, component/st-util, error/flash-loader, error/gdb-server, os/linux, programmer/stlinkv2-1, status/resolved, target/stm32f0
