### ISSUE TITLE
STM32F103C8T8: Wrong flash size determined after debugging

### ISSUE THREAD

**Issue by martonmiklos** [stlink-org/stlink#659] opened 2017-12-11 16:16 UTC
- [X] Programmer/board type: Stlink/v2
- [X] Programmer firmware version: e.g STSW-LINK007 2.29.18 
- [X] Operating system: Linux: Ubuntu 14.04 
- [X] Stlink tools version and/or git commit hash: 19691485359afef1a256964afcbb8dcf4b733209
- [X] Stlink commandline tool name: st-flash
- [X] Target chip: STM32F103C8T8

After performing a debug session with openOCD+GDB I kill both process (OpenSTM32 does that).
Afterwards when I run the st-flash I got malformed readout and wrong flash size:

Output:

```
mm@mm-imac:~/Projektek/stlink$ ./st-flash --flash=64k read /tmp/out.hex 0x8004000 0xC000
st-flash 1.4.0-13-g1969148
2017-12-11T17:08:50 INFO common.c: Loading device parameters....
2017-12-11T17:08:50 INFO common.c: Device connected is: F1 Medium-density device, id 0x20036410
2017-12-11T17:08:50 INFO common.c: SRAM size: 0x5000 bytes (20 KiB), Flash: **0x1904000** bytes **(25616 KiB)** in pages of 1024 bytes
Forcing flash size: --flash=0x00010000
mm@mm-imac:~/Projektek/stlink$ ./st-flash --flash=64k read /tmp/out.hex 0x8004000 0xC000
st-flash 1.4.0-13-g1969148
2017-12-11T17:08:54 INFO common.c: Loading device parameters....
2017-12-11T17:08:54 INFO common.c: Device connected is: F1 Medium-density device, id 0x20036410
2017-12-11T17:08:54 INFO common.c: SRAM size: 0x5000 bytes (20 KiB), Flash: 0x10000 bytes (64 KiB) in pages of 1024 bytes
```
If I run the st-flash again it reads the correct flash size. 

Did anyone faced with  the similar issue?

**Comment by Nightwalker-87** [comment] 2020-02-21 12:29
Please verify if the problem still exists in Release v1.6.0.

**Comment by Nightwalker-87** [comment] 2020-03-21 15:21
@martonmiklos: Any progress on this?

**Comment by Nightwalker-87** [comment] 2020-04-14 15:55
Possibly related to issue 275.

**Comment by chenguokai** [comment] 2020-04-14 17:20
Some clues that I have found: 
0x6410 is one magic number used in openocd.
The decimal form, 25616, can be found as a part of the name of a SRAM chip, IS61WV25616EDBLL.

The one used in openocd is quite suspicious.

**Comment by Nightwalker-87** [comment] 2020-06-24 21:17
> Please verify if the problem still exists in Release v1.6.0.

@martonmiklos: Have you tested this? Please let us know.

**Comment by martonmiklos** [comment] 2020-06-30 09:42
I do not use the openOCD anymore, and I no longer have that STM32F103C8T8 based gear where this issue happened. I am closing this issue, in the case someone ran into this could be reopened and investigated again.

**Comment by Nightwalker-87** [comment] 2020-06-30 10:40
@martonmiklos: Please don't close tickets and leave this task to project maintenance.
This may prevent others from dealing with this and interferes with general ticket handling.
It's ok though, if you don't want to be involved in this issue any more.
We can take that into account and you can unsubscribe from this issue to avoid be notified on updates any longer.

**Comment by swiftgeek** [comment] 2020-07-11 04:45
Same issue but only with very particular unit of the STM32F103C8T8

**Comment by Nightwalker-87** [comment] 2020-07-17 20:11
@swiftgeek: Thanks for the feedback. I think this is not a satisfiable state and thus should be investigated.

**Comment by Nightwalker-87** [comment] 2020-12-14 22:08
@chenguokai: I still don't really understand what you explained before. What does that mean?

**Comment by Nightwalker-87** [comment] 2021-03-12 18:24
I followed the steps of @martonmiklos with the difference that I performed the debug session via `gdb-multiarch` in combination with `st-util` as described in our tutorial. The result below reveals that I was not able to reproduce the issue with v1.5.1:

```
$ sudo st-flash --flash=64k read /tmp/out.hex 0x8004000 0xC000
st-flash 1.5.1-1-gffa986c-dirty
2021-03-12T19:14:27 INFO common.c: Loading device parameters....
2021-03-12T19:14:27 INFO common.c: Device connected is: F1 Medium-density device, id 0x20036410
2021-03-12T19:14:27 INFO common.c: SRAM size: 0x5000 bytes (20 KiB), Flash: 0x10000 bytes (64 KiB) in pages of 1024 bytes
$ sudo st-flash --flash=64k read /tmp/out.hex 0x8004000 0xC000
st-flash 1.5.1-1-gffa986c-dirty
2021-03-12T19:14:31 INFO common.c: Loading device parameters....
2021-03-12T19:14:31 INFO common.c: Device connected is: F1 Medium-density device, id 0x20036410
2021-03-12T19:14:31 INFO common.c: SRAM size: 0x5000 bytes (20 KiB), Flash: 0x10000 bytes (64 KiB) in pages of 1024 bytes
```

I had to use v1.5.1 as I was not able to compile versions v1.4.0 and v1.5.0.
Nevertheless I may have a look if anything relevant to this topic happened between 19691485359afef1a256964afcbb8dcf4b733209 and v1.5.1.

**Comment by Nightwalker-87** [comment] 2021-03-12 18:25
I followed the steps of @martonmiklos with the difference that I performed the debug session via `gdb-multiarch` in combination with `st-util` as described in our tutorial. The result below reveals that I was not able to reproduce the issue with v1.5.1:

```
$ sudo st-flash --flash=64k read /tmp/out.hex 0x8004000 0xC000
st-flash 1.5.1-1-gffa986c-dirty
2021-03-12T19:14:27 INFO common.c: Loading device parameters....
2021-03-12T19:14:27 INFO common.c: Device connected is: F1 Medium-density device, id 0x20036410
2021-03-12T19:14:27 INFO common.c: SRAM size: 0x5000 bytes (20 KiB), Flash: 0x10000 bytes (64 KiB) in pages of 1024 bytes
$ sudo st-flash --flash=64k read /tmp/out.hex 0x8004000 0xC000
st-flash 1.5.1-1-gffa986c-dirty
2021-03-12T19:14:31 INFO common.c: Loading device parameters....
2021-03-12T19:14:31 INFO common.c: Device connected is: F1 Medium-density device, id 0x20036410
2021-03-12T19:14:31 INFO common.c: SRAM size: 0x5000 bytes (20 KiB), Flash: 0x10000 bytes (64 KiB) in pages of 1024 bytes
```

I had to use v1.5.1 as I was not able to compile versions v1.4.0 and v1.5.0.
Nevertheless I may have a look if anything relevant to this topic happened between 19691485359afef1a256964afcbb8dcf4b733209 and v1.5.1.

**Comment by Nightwalker-87** [comment] 2021-03-12 18:27
I followed the steps of @martonmiklos with the difference that I performed the debug session via `gdb-multiarch` in combination with `st-util` as described in our tutorial. The result below reveals that I was not able to reproduce the issue with v1.5.1:

```
$ sudo st-flash --flash=64k read /tmp/out.hex 0x8004000 0xC000
st-flash 1.5.1-1-gffa986c-dirty
2021-03-12T19:14:27 INFO common.c: Loading device parameters....
2021-03-12T19:14:27 INFO common.c: Device connected is: F1 Medium-density device, id 0x20036410
2021-03-12T19:14:27 INFO common.c: SRAM size: 0x5000 bytes (20 KiB), Flash: 0x10000 bytes (64 KiB) in pages of 1024 bytes
$ sudo st-flash --flash=64k read /tmp/out.hex 0x8004000 0xC000
st-flash 1.5.1-1-gffa986c-dirty
2021-03-12T19:14:31 INFO common.c: Loading device parameters....
2021-03-12T19:14:31 INFO common.c: Device connected is: F1 Medium-density device, id 0x20036410
2021-03-12T19:14:31 INFO common.c: SRAM size: 0x5000 bytes (20 KiB), Flash: 0x10000 bytes (64 KiB) in pages of 1024 bytes
```

I had to use v1.5.1 as I was not able to compile versions v1.4.0 and v1.5.0.
Nevertheless I may have a look if anything relevant to this topic happened between 19691485359afef1a256964afcbb8dcf4b733209 and v1.5.1.

**Comment by Nightwalker-87** [comment] 2021-03-26 21:02
I couldn't find anything relevant from the git tree between the mentioned commits.
The reporting of wrong flash sizes may appear on single chips which are partly defective or faked.
As this issue could not be reproduced we can now safely close it as resolved.

**Closed by Nightwalker-87** 2021-03-26 21:02 UTC
Labels: component/st-flash, os/linux, programmer/stlinkv2, status/no-bug, status/resolved, target/stm32f1
